-- Esta migracion quedo vacia a proposito: la tabla "descuentos_categoria" ya fue
-- creada por la migracion 0_init (duplicado por error historico). El contenido
-- original volvia a crear la misma tabla, lo que rompia "prisma migrate dev" en
-- cualquier base de datos 100% fresca (shadow DB incluida) con el error P3006
-- "relation already exists". No se elimina el archivo para no invalidar el
-- checksum de esta migracion ya aplicada en las bases de datos reales.
